#!/usr/bin/env bash
# =============================================================================
# orchestrate.sh — Mission Control Orchestrator
# =============================================================================
# Runs via cron every 5 minutes. Reads mission-control-tasks/state.json,
# routes tasks through the 5-stage pipeline, delegates work to team agents
# via Claude, and updates state atomically.
#
# Generated by: github.com/fidevz/skills — mission-control
# Project: {{PROJECT_NAME}}
# =============================================================================

set -euo pipefail

# Ensure Homebrew and nvm binaries are on PATH (cron runs with minimal environment)
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:$PATH"

# -----------------------------------------------------------------------------
# Config
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOCK_FILE="$SCRIPT_DIR/.orchestrator.lock"
STATE_FILE="$SCRIPT_DIR/state.json"
PLANS_DIR="$SCRIPT_DIR/plans"
LOG_FILE="$SCRIPT_DIR/orchestrate.log"
TIMEOUT=3300  # 55 minutes — cron runs every 5 min, tasks can be long

# ntfy.sh push notifications
NTFY_TOPIC="${NTFY_TOPIC:-{{NTFY_TOPIC_DEFAULT}}}"
NTFY_URL="https://ntfy.sh/${NTFY_TOPIC}"

# -----------------------------------------------------------------------------
# Logging
# Writes to the log file with UTC ISO timestamp prefix.
# -----------------------------------------------------------------------------
log() {
  echo "[$(date -u +%FT%TZ)] [$1] $2" >> "$LOG_FILE"
}

# -----------------------------------------------------------------------------
# Push notification via ntfy.sh
# Usage: notify "title" "message" [priority] [tags]
# priority: default | high | urgent
# tags:     https://docs.ntfy.sh/emojis/
# -----------------------------------------------------------------------------
notify() {
  local title="$1"
  local msg="$2"
  local priority="${3:-default}"
  local tags="${4:-robot}"
  curl -s \
    -H "Title: $title" \
    -H "Priority: $priority" \
    -H "Tags: $tags" \
    -d "$msg" \
    "$NTFY_URL" > /dev/null 2>&1 || true
}

# -----------------------------------------------------------------------------
# Mutex via shlock (macOS built-in: /usr/bin/shlock)
# -----------------------------------------------------------------------------
if ! /usr/bin/shlock -f "$LOCK_FILE" -p $$; then
  log "SKIP" "Already running (PID $(cat "$LOCK_FILE" 2>/dev/null || echo '?'))"
  exit 0
fi
trap "rm -f '$LOCK_FILE'" EXIT

log "START" "Orchestrator acquired lock (PID $$)"

# -----------------------------------------------------------------------------
# Ensure plans/ directory exists
# -----------------------------------------------------------------------------
mkdir -p "$PLANS_DIR"

# -----------------------------------------------------------------------------
# Sanity check: state.json must exist and be valid JSON
# -----------------------------------------------------------------------------
[[ ! -f "$STATE_FILE" ]] && { log "ERROR" "state.json not found"; exit 0; }
jq empty "$STATE_FILE" 2>/dev/null || { log "ERROR" "state.json invalid JSON"; exit 0; }

# -----------------------------------------------------------------------------
# Heartbeat: update agents.orchestrator fields
# -----------------------------------------------------------------------------
NOW_UTC="$(date -u +%FT%TZ)"
jq --arg ts "$NOW_UTC" '.agents.orchestrator.heartbeat = $ts | .agents.orchestrator.status = "running"' \
  "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"

# -----------------------------------------------------------------------------
# Guard: check objective status
# -----------------------------------------------------------------------------
OBJECTIVE_STATUS="$(jq -r '.objective.status' "$STATE_FILE")"

if [[ "$OBJECTIVE_STATUS" != "active" ]]; then
  log "IDLE" "Objective status: $OBJECTIVE_STATUS"
  jq '.agents.orchestrator.status = "idle"' "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"
  if [[ "$OBJECTIVE_STATUS" == "done" || "$OBJECTIVE_STATUS" == "completed" ]]; then
    crontab -l 2>/dev/null | grep -v "orchestrate.sh" | crontab - 2>/dev/null || true
    log "IDLE" "Objective $OBJECTIVE_STATUS — orchestrator removed from crontab automatically"
  fi
  exit 0
fi

# -----------------------------------------------------------------------------
# Guard: check if all ACs verified
# -----------------------------------------------------------------------------
TOTAL_ACS="$(jq '.objective.acceptance_criteria | length' "$STATE_FILE")"
VERIFIED_ACS="$(jq '[.objective.acceptance_criteria[] | select(.verified == true)] | length' "$STATE_FILE")"

if [[ "$TOTAL_ACS" -gt 0 && "$TOTAL_ACS" -eq "$VERIFIED_ACS" ]]; then
  OBJECTIVE_TITLE="$(jq -r '.objective.title' "$STATE_FILE")"
  OBJECTIVE_ID="$(jq -r '.objective.id' "$STATE_FILE")"
  log "COMPLETE" "All $TOTAL_ACS ACs verified — objective completed"
  jq --arg ts "$(date -u +%FT%TZ)" \
    '.objective.status = "completed" | .objective.completed_at = $ts | .agents.orchestrator.status = "idle"' \
    "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"
  crontab -l 2>/dev/null | grep -v "orchestrate.sh" | crontab - 2>/dev/null || true
  log "COMPLETE" "Cron deactivated — activate next objective with /mission-control"
  notify "✅ $OBJECTIVE_ID completed" "$OBJECTIVE_TITLE — all ACs verified. Activate next objective with /mission-control" "high" "white_check_mark,tada"
  exit 0
fi

OBJECTIVE_TITLE="$(jq -r '.objective.title' "$STATE_FILE")"
OBJECTIVE_ID="$(jq -r '.objective.id' "$STATE_FILE")"

log "RUN" "Active objective — $VERIFIED_ACS/$TOTAL_ACS ACs verified"

# -----------------------------------------------------------------------------
# Load orchestrator prompt from ORCHESTRATOR.md
# -----------------------------------------------------------------------------
ORCHESTRATOR_PROMPT_FILE="$SCRIPT_DIR/ORCHESTRATOR.md"

if [[ ! -f "$ORCHESTRATOR_PROMPT_FILE" ]]; then
  log "ERROR" "ORCHESTRATOR.md not found — aborting"
  exit 0
fi

PROMPT=$(cat "$ORCHESTRATOR_PROMPT_FILE")
log "RUN" "Loaded orchestrator prompt ($(wc -l < "$ORCHESTRATOR_PROMPT_FILE") lines)"

# -----------------------------------------------------------------------------
# Invoke Claude
# -----------------------------------------------------------------------------
log "RUN" "Invoking claude orchestrator (timeout: ${TIMEOUT}s)..."

set +e

if command -v gtimeout &>/dev/null; then
  gtimeout "$TIMEOUT" claude --dangerously-skip-permissions -p "$PROMPT" 2>&1 | tee -a "$LOG_FILE"
elif command -v timeout &>/dev/null; then
  timeout "$TIMEOUT" claude --dangerously-skip-permissions -p "$PROMPT" 2>&1 | tee -a "$LOG_FILE"
else
  claude --dangerously-skip-permissions -p "$PROMPT" 2>&1 | tee -a "$LOG_FILE"
fi
CLAUDE_EXIT="${PIPESTATUS[0]}"

set -e

if [[ "$CLAUDE_EXIT" -eq 124 ]]; then
  log "WARN" "Claude timed out after ${TIMEOUT}s"
  notify "⏱ Timeout — $OBJECTIVE_ID" "Orchestrator took more than ${TIMEOUT}s. Next cycle in 5 min." "high" "clock1"
elif [[ "$CLAUDE_EXIT" -ne 0 ]]; then
  log "ERROR" "Claude exited with code $CLAUDE_EXIT"
  notify "❌ Error — $OBJECTIVE_ID" "Claude exited with code $CLAUDE_EXIT. Check mission-control-tasks/orchestrate.log" "urgent" "rotating_light"
fi

# -----------------------------------------------------------------------------
# Post-run: reset orchestrator status
# -----------------------------------------------------------------------------
jq '.agents.orchestrator.status = "idle"' "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"

VERIFIED_ACS_NOW="$(jq '[.objective.acceptance_criteria[] | select(.verified == true)] | length' "$STATE_FILE")"

log "END" "Cycle complete (exit: $CLAUDE_EXIT) — ACs: $VERIFIED_ACS_NOW/$TOTAL_ACS"

if [[ "$CLAUDE_EXIT" -eq 0 ]]; then
  notify "🔄 Cycle complete — $OBJECTIVE_ID" "ACs: $VERIFIED_ACS_NOW/$TOTAL_ACS verified" "default" "robot"
fi

exit 0
